# Configuration for Travis CI Continuous Integration Service
#
# Build status: https://travis-ci.org/Illumina/interop
#
# Tested configurations:
#
#   Linux Clang 3.7
#     - Release/Debug
#   Linux GCC
#     - Release/Debug
#     - 4.6/4.9
#   OSX Clang
#     - Release/Debug
#
# No support for 32-bit Linux
#
# TODO: For Python wheels, support: https://github.com/pypa/manylinux
# TODO: Create individual builds for each language

language: cpp
sudo: required

matrix:
  include:
  - os: osx
    compiler: clang
    env: DEPLOY_BUILD=true SCRIPT="bash ./tools/package_osx.sh $PWD $PWD/dist travis"
  - os: linux
    compiler: clang
    env: SCRIPT="bash ./tools/test.sh ON Debug travis"
  - os: linux
    compiler: gcc
    env: SCRIPT="bash ./tools/test.sh ON Debug travis"
  - os: linux
    compiler: gcc
    sudo: required
    services:
      - docker
    env: DEPLOY_BUILD=true DOCKER_IMAGE=ezralanglois/interop SCRIPT="docker run --rm -v $PWD:/io ezralanglois/interop sh /io/tools/package_linux.sh /io /io/dist"
  - os: osx
    compiler: clang
    env: SCRIPT="bash ./tools/test.sh OFF Debug travis"
  - os: linux
    compiler: gcc
    addons: &1
      apt:
        sources:
        - george-edison55-precise-backports
        - ubuntu-toolchain-r-test
        - sourceline: 'ppa:teward/swig3.0'
        packages:
        - g++-5
        - libicu-dev
        - swig3.0
        - doxygen
        - graphviz
        - mono-complete
        - libgtest-dev
        - python-numpy
    env: COMPILER_VERSION=-5 SCRIPT="bash ./tools/test.sh ON Debug travis"
  - os: linux
    compiler: clang
    addons: &2
      apt:
        sources:
        - george-edison55-precise-backports
        - ubuntu-toolchain-r-test
        - llvm-toolchain-precise-3.7
        - sourceline: 'ppa:teward/swig3.0'
        packages:
        - g++-4.9
        - clang-3.7
        - libicu-dev
        - swig3.0
        - doxygen
        - graphviz
        - mono-complete
        - libgtest-dev
        - python-numpy
    env: COMPILER_VERSION=-3.7 SCRIPT="bash ./tools/test.sh ON Debug travis"
addons:
  apt:
    sources:
    - george-edison55-precise-backports
    - sourceline: 'ppa:teward/swig3.0'
    packages:
    - libicu-dev
    - swig3.0
    - doxygen
    - graphviz
    - mono-complete
    - libgtest-dev
    - python-numpy
cache:
  directories:
    - $HOME/NUnit-2.6.4
    - $HOME/cmake

install:
- if test "$TRAVIS_OS_NAME" = "linux"; then source tools/travis-linux-install.sh ; fi
- if test "$TRAVIS_OS_NAME" = "osx"; then source tools/travis-osx-install.sh ; fi
- if [ ! -z $DOCKER_IMAGE ]; then docker pull $DOCKER_IMAGE ; fi
- ls $HOME/NUnit-2.6.4

before_script:
- export CC="${COMPILER_HOME}${CC}${COMPILER_VERSION}"
- export CXX="${COMPILER_HOME}${CXX}${COMPILER_VERSION}"
- if test "$PYTHON_VERSION_NUM" != "System"; then export PATH="$HOME/miniconda_${PYTHON_VERSION_NUM}/bin:$PATH" ; fi
- if test "$TRAVIS_OS_NAME" = "linux"; then export PATH="$HOME/cmake/bin:${PATH}" ; fi
- cmake -version
- which $CC
- which $CXX
- echo "HOME=$HOME"
- echo "PWD=$PWD"

script:
- $SCRIPT

#white list broke the tag push deployment

branches:
  only:
  - master
  - /v\d\.\d\.\d/

notifications:
  email: false
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: "EefkqiGLBE+vHGyLIS5/VvmHPSnJCVKuUlS4+9A+7zg7uWscr7UOmyO/Fwo/RbmrCR7KV02/c9J8hiUiKcjs4ne0m65NtsT8mo7mDQCMwqGtgfBukVvi1C0AdD2g/ztAG/KMkhfk5WTTkSn3LkLy5R2P2cZ4RMfuALyJfUw9Xhs/2CK2RnTgtyKeDjwT1WaB7EoWB0wSPoDJVZR8AeygZNRwaDde20V8pax2+e4MXQh9d0Wj0lO4VpnFQp0TrvTQPKZKrYYeMIdR2e8HAG++xLMsZ4T5SYA3EuDQjyLP5rb1AE1IBbrd4tcUh/0sURQ+uR7y32eGErCQ/+JnrLGnH2xZklh9PYHaV4gkseJJpcnhko11HzxEuWfRj4qGZrMkmq3DdrGCsCGA+MnsT0oTqiexuOKWvpSLAJATeco1yOSoJ6IYvi2tYTJYMxzsPtOMcvAhi1MBpuyZeRIygGgz7wD2tysTVLRUYTVL25f7sVBvz9BpPQGdRtuDLVTnu8b1hS5w9vLncrNnxk+dlCYufzoTmwJ4D3IsL5kXl9/DrgDlkxfIz5/R4iA/vDccGvqdklBk47fW3pF9ATxUMIw86USlRbb0yecSTgNsqd+Si0RKwJ7Jchpj0CPeiKIoMXChxnOOJesY4ROhhpCqVif2LBN8w5yt4B4gHJ9T0TY6k1E="
  file_glob: true
  file: $PWD/dist/*.*
  on:
    repo: ezralanglois/interop
    branch: master
    tags: true
    condition:
      - "$DEPLOY_BUILD == true"
