# Configuration for Travis CI Continuous Integration Service
#
# Build status: https://travis-ci.org/Illumina/interop
#
# Tested configurations:
#
#   Linux Clang 3.7
#     - Release/Debug
#   Linux GCC
#     - Release/Debug
#     - 4.6/4.9
#   OSX Clang
#     - Release/Debug
#
# No support for 32-bit Linux
#

language: cpp
sudo: required

matrix:
  include:
  - compiler: clang
    os: linux
    env: INTEROP_C89=ON BUILD_TYPE=Debug BUILD_NAME=linux_clang34_debug
  - compiler: clang
    os: linux
    env: INTEROP_C89=ON BUILD_TYPE=Release BUILD_NAME=linux_clang34_release
  - compiler: gcc
    os: linux
    env: INTEROP_C89=ON BUILD_TYPE=Debug BUILD_NAME=linux_gcc46_debug
  - compiler: gcc
    os: linux
    env: INTEROP_C89=ON BUILD_TYPE=Release BUILD_NAME=linux_gcc46_release DEPLOY_BUILD=true
  - compiler: gcc
    addons: &1
      apt:
        sources:
        - george-edison55-precise-backports
        - ubuntu-toolchain-r-test
        - sourceline: 'ppa:teward/swig3.0'
        packages:
        - cmake
        - cmake-data
        - g++-5
        - libicu-dev
        - swig3.0
        - doxygen
        - graphviz
        - mono-complete
        - libgtest-dev
    env: INTEROP_C89=OFF COMPILER_VERSION=-5 BUILD_TYPE=Debug BUILD_NAME=linux_gcc52_debug
    os: linux
  - compiler: gcc
    addons: *1
    env: INTEROP_C89=OFF COMPILER_VERSION=-5 BUILD_TYPE=Release BUILD_NAME=linux_gcc52_release
    os: linux
  - compiler: clang
    addons: &2
      apt:
        sources:
        - george-edison55-precise-backports
        - ubuntu-toolchain-r-test
        - llvm-toolchain-precise-3.7
        - sourceline: 'ppa:teward/swig3.0'
        packages:
        - cmake
        - cmake-data
        - g++-4.9
        - clang-3.7
        - libicu-dev
        - swig3.0
        - doxygen
        - graphviz
        - mono-complete
        - libgtest-dev
    env: INTEROP_C89=OFF COMPILER_VERSION=-3.7 BUILD_TYPE=Debug BUILD_NAME=linux_clang37_debug
    os: linux
  - compiler: clang
    addons: *2
    env: INTEROP_C89=OFF COMPILER_VERSION=-3.7 BUILD_TYPE=Release BUILD_NAME=linux_clang37_release
    os: linux
  - compiler: clang
    os: osx
    env: INTEROP_C89=OFF BUILD_TYPE=Debug BUILD_NAME=osx_clang_debug
  - compiler: clang
    os: osx
    env: INTEROP_C89=OFF BUILD_TYPE=Release BUILD_NAME=osx_clang_release DEPLOY_BUILD=true
addons:
  apt:
    sources:
    - george-edison55-precise-backports
    - sourceline: 'ppa:teward/swig3.0'
    packages:
    - cmake
    - cmake-data
    - libicu-dev
    - swig3.0
    - doxygen
    - graphviz
    - mono-complete
    - libgtest-dev
cache:
  directories:
    - $HOME/NUnit-2.6.4

install:
- if test "$TRAVIS_OS_NAME" = "linux"; then source tools/travis-linux-install.sh; fi
- if test "$TRAVIS_OS_NAME" = "osx"; then source tools/travis-osx-install.sh; fi
- ls -la $(which $CC)
- ls -la $(which $CXX)
- ls $HOME/NUnit-2.6.4

before_script:
- rm -fr build
- mkdir -p build
- cd build
- export CC="${CC}${COMPILER_VERSION}"
- export CXX="${CXX}${COMPILER_VERSION}"
- export PATH="$HOME/miniconda/bin:$PATH"

script:
- export BUILD_PATH=${PWD}/${BUILD_NAME}
- export PYTHON_BUILD_PATH=${PWD}/dist
- echo 'Configuring...' && echo -en 'travis_fold:start:script.1\\r'
- cmake -DNUNIT_ROOT=$HOME/NUnit-2.6.4 ../ -DENABLE_BACKWARDS_COMPATIBILITY=$INTEROP_C89 -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_INSTALL_PREFIX=${BUILD_PATH} -DPACKAGE_OUTPUT_FILE_PREFIX=${PYTHON_BUILD_PATH}
- echo -en 'travis_fold:end:script.1\\r'
- cmake --build .
- echo 'Installing...' && echo -en 'travis_fold:start:script.2\\r'
- make install
- echo -en 'travis_fold:end:script.2\\r'
- cmake --build . --target check
- echo 'Package Python' && echo -en 'travis_fold:start:script.3\\r'
- cmake --build . --target package_wheel
- echo 'Cleaning...' && echo -en 'travis_fold:start:script.3\\r'
- make clean
- echo -en 'travis_fold:end:script.3\\r'

#white list broke the tag push deployment

branches:
  only:
  - master
  - /v\d\.\d\.\d/

notifications:
  email: false
before_deploy:
- cd `dirname ${BUILD_PATH}`
- tar czf interop-${BUILD_NAME}.tar.gz ${BUILD_NAME}
- export PYTHON_PACKAGE_NAME=`find $PYTHON_BUILD_PATH -name "*.whl"`
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: "VNViXof52Nnfi6yN0/eVY7BhRgK25ObuGsbVAXqbnl/ai40QiRwp6RXZ3xsVjSpDvKBhNrNJONLISak5KbnYu9ydQDHw880lfl0ceYXUM6qpGNBc+euxcbi5OM7CRHp3MGKujQRM2rXOuoTF73LxU7jtDHiwKFgd+Hr8D4xCWc76jcSaax4dmL4lcp3x2sjISSl1qlpMtXbUAY99td5kWJHuQIMTlX9fQy1GylePPz/7d+ARkzwVzzdcpCiEdfQH5cW8YWajWeuXYy5UvZdfUQKUIW29gEKGTTyLzRLE8Pjohi/SNbO/C6S6gkUV8FI6cHXo/eTZtzU3YtpdtTcKInm1CueA4hz54CY8YuwfAgHcDNeD5yYeWBe3882PvUbZGumb1LXAg8r5s0U4VP6Xlp+mfyllCObdhxcVExFc13A28UTlkXEX7uwDl8cDWHK6b50qNH3wtnDaIh0uqES53eo77N1YJMk6+AXqAZCLyg6tEvIBs5b0r9ZgnsssveHAo9HeK7NNXabGKjv64hA9YxSAlfibqVHZuCd7tg1M9dc+uqEYZ2oCUyl6zEVgj7y7b0g5jOd3J3AOUp1ggJj6tlOWZGVjMjRcqn/Bsc8iQ9L44tKCqDLLZdd7/BPeODfbiAiwa0WJNUi2V51XKzAt7eGocp6pEtcbmCUFfigwoAw="
  file:
    - interop-${BUILD_NAME}.tar.gz
    - ${PYTHON_PACKAGE_NAME}
  on:
    repo: Illumina/interop
    branch: master
    tags: true
    condition:
      - "$DEPLOY_BUILD == true"
