# Configuration for Travis CI Continuous Integration Service
#
# Build status: https://travis-ci.org/Illumina/interop
#
# Tested configurations:
#
#   Linux Clang 3.7
#     - Release/Debug
#   Linux GCC
#     - Release/Debug
#     - 4.6/4.9
#   OSX Clang
#     - Release/Debug
#
# No support for 32-bit Linux
#
# TODO: For Python wheels, support: https://github.com/pypa/manylinux
# TODO: Create individual builds for each language

language: cpp
sudo: required

matrix:
  include:
  - os: osx
    compiler: clang
    env: DEPLOY_BUILD=true SCRIPT="bash ./tools/package_osx.sh $PWD $PWD/dist travis"
  - os: linux
    compiler: clang
    env: SCRIPT="bash ./tools/test.sh ON Debug travis"
  - os: linux
    compiler: gcc
    env: SCRIPT="bash ./tools/test.sh ON Debug travis"
  - os: linux
    compiler: gcc
    sudo: required
    services:
      - docker
    env: DEPLOY_BUILD=true DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64 SCRIPT="docker run --rm -v $PWD:/io quay.io/pypa/manylinux1_x86_64 sh /io/tools/package_linux.sh /io /io/dist"
  - os: osx
    compiler: clang
    env: SCRIPT="bash ./tools/test.sh OFF Debug travis"
  - os: linux
    compiler: gcc
    addons: &1
      apt:
        sources:
        - george-edison55-precise-backports
        - ubuntu-toolchain-r-test
        - sourceline: 'ppa:teward/swig3.0'
        packages:
        - g++-5
        - libicu-dev
        - swig3.0
        - doxygen
        - graphviz
        - mono-complete
        - libgtest-dev
        - python-numpy
    env: COMPILER_VERSION=-5 SCRIPT="bash ./tools/test.sh ON Debug travis"
  - os: linux
    compiler: clang
    addons: &2
      apt:
        sources:
        - george-edison55-precise-backports
        - ubuntu-toolchain-r-test
        - llvm-toolchain-precise-3.7
        - sourceline: 'ppa:teward/swig3.0'
        packages:
        - g++-4.9
        - clang-3.7
        - libicu-dev
        - swig3.0
        - doxygen
        - graphviz
        - mono-complete
        - libgtest-dev
        - python-numpy
    env: COMPILER_VERSION=-3.7 SCRIPT="bash ./tools/test.sh ON Debug travis"
addons:
  apt:
    sources:
    - george-edison55-precise-backports
    - sourceline: 'ppa:teward/swig3.0'
    packages:
    - libicu-dev
    - swig3.0
    - doxygen
    - graphviz
    - mono-complete
    - libgtest-dev
    - python-numpy
cache:
  directories:
    - $HOME/NUnit-2.6.4
    - $HOME/cmake

install:
- if test "$TRAVIS_OS_NAME" = "linux"; then source tools/travis-linux-install.sh ; fi
- if test "$TRAVIS_OS_NAME" = "osx"; then source tools/travis-osx-install.sh ; fi
- if [ ! -z $DOCKER_IMAGE ]; then docker pull $DOCKER_IMAGE ; fi
- ls $HOME/NUnit-2.6.4

before_script:
- export CC="${COMPILER_HOME}${CC}${COMPILER_VERSION}"
- export CXX="${COMPILER_HOME}${CXX}${COMPILER_VERSION}"
- if test "$PYTHON_VERSION_NUM" != "System"; then export PATH="$HOME/miniconda_${PYTHON_VERSION_NUM}/bin:$PATH" ; fi
- if test "$TRAVIS_OS_NAME" = "linux"; then export PATH="$HOME/cmake/bin:${PATH}" ; fi
- cmake -version
- which $CC
- which $CXX
- echo "HOME=$HOME"
- echo "PWD=$PWD"

script:
- $SCRIPT

#white list broke the tag push deployment

branches:
  only:
  - master
  - /v\d\.\d\.\d/

notifications:
  email: false
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: VNViXof52Nnfi6yN0/eVY7BhRgK25ObuGsbVAXqbnl/ai40QiRwp6RXZ3xsVjSpDvKBhNrNJONLISak5KbnYu9ydQDHw880lfl0ceYXUM6qpGNBc+euxcbi5OM7CRHp3MGKujQRM2rXOuoTF73LxU7jtDHiwKFgd+Hr8D4xCWc76jcSaax4dmL4lcp3x2sjISSl1qlpMtXbUAY99td5kWJHuQIMTlX9fQy1GylePPz/7d+ARkzwVzzdcpCiEdfQH5cW8YWajWeuXYy5UvZdfUQKUIW29gEKGTTyLzRLE8Pjohi/SNbO/C6S6gkUV8FI6cHXo/eTZtzU3YtpdtTcKInm1CueA4hz54CY8YuwfAgHcDNeD5yYeWBe3882PvUbZGumb1LXAg8r5s0U4VP6Xlp+mfyllCObdhxcVExFc13A28UTlkXEX7uwDl8cDWHK6b50qNH3wtnDaIh0uqES53eo77N1YJMk6+AXqAZCLyg6tEvIBs5b0r9ZgnsssveHAo9HeK7NNXabGKjv64hA9YxSAlfibqVHZuCd7tg1M9dc+uqEYZ2oCUyl6zEVgj7y7b0g5jOd3J3AOUp1ggJj6tlOWZGVjMjRcqn/Bsc8iQ9L44tKCqDLLZdd7/BPeODfbiAiwa0WJNUi2V51XKzAt7eGocp6pEtcbmCUFfigwoAw=
  file:
  - $PWD/dist/*.tar.gz
  - $PWD/dist/*manylinux1_x86_64.whl
  on:
    repo: ezralanglois/interop
    branch: master
    tags: true
    condition:
      - "$DEPLOY_BUILD == true"
